# Pin upstream shell scripts and tmux plugins for reproducible installs.
[".tmux/plugins/tmux-fzf"]
    type = "archive"
    url = "https://github.com/sainnhe/tmux-fzf/archive/e5f427e9dcf180ca92e2f8af47ba07f644fd4585.tar.gz"
    stripComponents = 1
    checksum.sha256 = "2e9459371e38b3e17585b229c82dd25fc0b5567a9dc4a647238fcede6cf2ff9f"

[".tmux/plugins/extrakto"]
    type = "archive"
    url = "https://github.com/laktak/extrakto/archive/d1af77988081dae496fa4a1f5e5e6bc9ef66767f.tar.gz"
    stripComponents = 1
    checksum.sha256 = "1042858558b14f77993b0d576b381abd86ed0cd52f4a10d60928fbc7a0d24429"

[".tmux/plugins/nord-tmux"]
    type = "archive"
    url = "https://github.com/nordtheme/tmux/archive/f7b6da07ab55fe32ee5f7d62da56d8e5ac691a92.tar.gz"
    stripComponents = 1
    checksum.sha256 = "f39aa6564fe25847ace037b398f2b69d67e4d50974118a9ee7602eccf62cb8c6"

[".config/zsh/prompts/prompt_igloo_setup"]
    type = "file"
    url = "https://raw.githubusercontent.com/arcticicestudio/igloo/84471d2dfead01fd2c5327f26d17a0357c4a7139/snowblocks/zsh/lib/themes/igloo.zsh"
    checksum.sha256 = "3ca1a9409059fef674bdbc7ef3c465316934d9a08cd60a8a24930c88db59e7e9"

[".config/zsh/git-prompt.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/94f057755b7941b321fd11fec1b2e3ca5313a4e0/contrib/completion/git-prompt.sh"
    checksum.sha256 = "7ff718f4a06fd0a0be7edfef926abb41b1353c48c1515ad312d226965b74943a"
