# Retain the standard Ctrl-b prefix.
set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Split panes in the current working directory.
bind-key '|' split-window -h -c '#{pane_current_path}'
bind-key '-' split-window -v -c '#{pane_current_path}'
bind-key r source-file ~/.tmux.conf \; display-message 'tmux config reloaded'
